import { createSlice } from "@reduxjs/toolkit";

interface UserData{
  token?:string | null
  id: string | null 
}

// Define the initial state interface
interface InitialState {
  userData: UserData;
}

// Initial state of the authSlice
const initialState: InitialState = {
  userData: {
    token: localStorage.getItem("userToken"), // Initialize user token from local storage
    id: localStorage.getItem("userId")
  },
};

// Create a slice for authentication
const authSlice = createSlice({
  name: "authSlice", // Name of the slice
  initialState, // Initial state
  reducers: {
    // Reducer to set authentication user data
    setAuthUser: (state: InitialState, { payload }) => ({
      ...state,
      userData: payload
    }),
  },
});

// Export the reducer generated by createSlice
export default authSlice.reducer;

// Export actions generated by createSlice
export const { setAuthUser } = authSlice.actions;
