import { createSlice, Draft, PayloadAction } from "@reduxjs/toolkit";

interface Course {
  id: number;
  title: string;
  description: string;
  department: string;
  credits: number;
}

// Define the initial state interface
interface InitialState {
  courseList: Course[];
  loading: boolean;
}

// Initial state of the courseSlice
const initialState: InitialState = {
  courseList: [],
  loading: false,
};

const courseSlice = createSlice({
  name: "courseSlice", // Name of the slice
  initialState, // Initial state
  reducers: {
    setCourseList: (state: any, { payload }) => ({
      ...state,
      courseList: payload,
    }),
    setLoading: (state: Draft<InitialState>, action: PayloadAction<any>) => ({
      ...state,
      loading: action.payload,
    }),
  },
});

// Export the reducer generated by createSlice
export default courseSlice.reducer;

// Export actions generated by createSlice
export const { setCourseList, setLoading } = courseSlice.actions;
