import { createSlice } from "@reduxjs/toolkit";



interface Notifications{
  message?: string
} 

// Define the initial state interface
interface InitialState {
  userNotifications: Notifications; // Type for user notifications
}

// Initial state of the userNotificationSlice
const initialState: InitialState = {
  userNotifications: {}, // Initial value for user notifications
};

// Create a slice for managing user notifications
const userNotificationSlice = createSlice({
  name: "userNotificationSlice", // Name of the slice
  initialState, // Initial state
  reducers: {
    // Reducer to add a new notification
    addNotification: (state: InitialState, { payload }) => ({
      ...state,
      userNotifications: payload, // Set userNotifications to the payload
    }),
    // Reducer to clear all notifications
    clearNotification: (state: InitialState) => ({ ...state, userNotifications: {} }), // Clear userNotifications
  },
});

// Export the reducer generated by createSlice
export default userNotificationSlice.reducer;

// Export actions generated by createSlice
export const { addNotification, clearNotification } = userNotificationSlice.actions;
